from dataclasses import dataclass, field

@dataclass
class OldEevee_Bloom_Names:
    """
    Class to store the names of various nodes and sockets used in the bloom node group
    """
    OE_Bloom: str = "OE_Bloom"
    Image: str = "Image"
    Color: str = "Color"
    Quality: str = "Quality"
    Knee: str = "Knee"
    Threshold: str = "Threshold"
    Radius: str = "Radius"
    Intensity: str = "Intensity"
    Clamp: str = "Clamp"
    Other: str = "Other"
    Hue: str = "Hue"
    Saturation: str = "Saturation"
    Fac: str = "Fac"
    Composite: str = "Composite"
    Viewer: str = "Viewer"
    Blur: str = "Blur"
    BM_Clamp: str = "BM Clamp"
    KM_Clamp: str = "KM Clamp"
    CR_Clamp: str = "CR Clamp"
    IY_Clamp: str = "IY Clamp"
    Clamp_Mix: str = "Clamp Mix"
    Blur_Mix: str = "Blur Mix"
    Bloom_Size: str = "Bloom Size"
    Group_Output: str = "Group Output"
    Group_Input_00: str = "Group Input 00"
    Original_Bloom_High: str = "Original Bloom High"
    Knee_Bloom_High: str = "Knee Bloom High"
    Knee_Mix: str = "Knee Mix"
    Group_Input_01: str = "Group Input 01"
    Group_Input_02: str = "Group Input 02"
    Group_Input_03: str = "Group Input 03"
    Group_Input_04: str = "Group Input 04"
    Group_Input_05: str = "Group Input 05"
    Bloom_High_Low: str = "Bloom High && Low"
    Knee_Bloom_Low: str = "Knee Bloom Low"
    KB_Switch: str = "KB Switch"
    OB_Switch: str = "OB Switch"
    Original_Bloom_Low: str = "Original Bloom Low"
    Reroute_00: str = "Reroute_00"
    Reroute_01: str = "Reroute_01"
    Render_Layers: str = "Render Layers"
    Bloom_Mute_Unmute: str = "Bloom Mute/Unmute"
    Real_Time_Compositing: str = "Real-Time Compositor"
    Enable_Compositor: str = "Enable Compositor"