from dataclasses import dataclass, field

@dataclass
class OldEevee_Bloom_Descr:
    """
    Class to store all the descriptions of the Bloom properties
    """
    image: str = "Standard color output"
    quality: str = "If the value is set to 0 then the bloom effect will be applied to the low resolution copy of the image. If the value is set to 1 then the bloom effect will be applied to the high resolution copy of the image. This can be helpful to save render times while only doing preview renders"
    threshold: str = "Filters out pixels under this level of brightness"
    knee: str = "Makes transition between under/over-threshold gradual"
    radius: str = "Bloom spread distance"
    color: str = "Color applied to the bloom effect"
    intensity: str = "Blend factor"
    clamp: str = "Maximum intensity a bloom pixel can have"
    other: str = "Additional options for customizing the bloom effect"
    hue: str = "The hue rotation offset, from 0 (-180°) to 1 (+180°). Note that 0 and 1 have the same result"
    saturation: str = "A value of 0 removes color from the image, making it black-and-white. A value greater than 1.0 increases saturation"
    fac: str = "The amount of influence the node exerts on the image"
    disabled: str = "The compositor is disabled"
    camera: str = "The compositor is enabled only in camera view"
    always: str = "The compositor is always enabled regardless of the view"
    node_ot_bloom: str = "Replication of the legacy eevee bloom option, but can be used in cycles as well"
    prop_pt_bloom: str = "Old Eevee Bloom In Both Eevee And Cycles"
    scene_ot_enable_compositor: str = "Enable the compositing node tree"
    blur_mix: str = "The optional Size input will be multiplied with the X and Y blur radius values. It also accepts a value image, to control the blur radius with a mask. The values should be mapped between (0 to 1) for an optimal effect"
    bloom_size: str = "Scale of the glow relative to the size of the image. 9 means the glow can cover the entire image, 8 means it can only cover half the image, 7 means it can only cover quarter of the image, and so on."
    bloom_mute_unmute_bool: str = "Toggle the bloom effect on or off"
    oe_bloom: str = "Replication of the legacy eevee bloom option"
    clamp_mix: str = "Clamps of each mix nodes in the oe_bloom node group"
    bm_clamp: str = "Blur Mix Clamp"
    km_clamp: str = "Knee Mix Clamp"
    cr_clamp: str = "Color Clamp"
    iy_clamp: str = "Intensity Clamp"
    real_time_compositing: str = "When to preview the compositor output inside the viewport"